env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
  project:
    - tsconfig.json
plugins:
  - '@typescript-eslint'
rules: {}
