language: node_js
node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - mkdir -p build
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script:
  - docker exec -it emscripten cmake -S . -B ./build
  - docker exec -it emscripten make -C ./build
