# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  wasm-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v11
    - name: mkdir
      run: mkdir -p build
      working-directory: WasmModule
    - name: cmake
      run: emcmake cmake -S ./ -B ./build
      working-directory: WasmModule
    - name: make
      run: emmake make -C ./build
      working-directory: WasmModule
  
  react-build:
    needs: wasm-build
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    - name: install
      run: npm install
      working-directory: client
    - name: lint
      run: npm run lint
      working-directory: client
    - name: test
      run: npm run test
      working-directory: client
    - name: build
      run: npm run build --if-present
      working-directory: client
    - name: deploy
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        # Build directory to deploy
        build_dir: client/build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
