# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  react-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'
        cache-dependency-path: react-client/yarn.lock

    - name: install
      run: cd react-client && yarn
      # working-directory: react-client
    - name: lint
      run: yarn lint
      # working-directory: react-client
    # - name: test
    #   run: npm run test
    #   working-directory: react-client
    - name: build
      run: yarn build
      # working-directory: react-client

    - name: upload-react-build
      uses: actions/upload-artifact@v2
      with:
        name: react-client-build
        path: ./build


  gh-pages:
    needs: react-build
    runs-on: ubuntu-latest
    
    steps:
    - name: download-react-build
      uses: actions/download-artifact@v2
      with:
        name: react-client-build
        path: ./build

    - name: deploy
      uses: crazy-max/ghaction-github-pages@v2
      with:
        # Build directory to deploy
        build_dir: ./build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
