# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  wasm-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v11
      - name: mkdir
        run: mkdir -p WasmModule/build
      - name: cmake
        run: emcmake cmake -S WasmModule -B WasmModule/build
      - name: make
        run: emmake -C WasmModule/build

    
  nodejs-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: chdir
      run: cd client
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: install
      run: npm install
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test
    - name: build
      run: npm run build --if-present
    - name: deploy
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        # Build directory to deploy
        build_dir: client/build
