# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  wasm-build:
    runs-on: ubuntu-latest
    container:
      image: trzeci/emscripten:sdk-incoming-64bit
      volumes: 
        - GomokuCore:/src
    steps:
      - name: Create build directory
        run: mkdir -p ./build && echo $(pwd)
      - name: CMake
        run: cmake -S ./ -B ./build
      - name: Make
        run: make -C ./build
    
#   nodejs-build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x, 16.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test
